    <link rel="stylesheet" href="libs/foundation/css/foundation.css">
    <link rel="stylesheet" href="libs/font-awesome/css/font-awesome.css">
    
    <link rel="stylesheet" href="main.css">
    
    <script src="libs/jquery/dist/jquery.js"></script>
    <script src="libs/modernizr/modernizr.js"></script>
    <script src="libs/angular/angular.js"></script>
    <script src="libs/angulartics/src/angulartics.js"></script>
    <script src="libs/angulartics-google-analytics/dist/angulartics-google-analytics.min.js"></script>    

    <script type="text/javascript" src="_main.js"></script>